[project]
name = "vbase-rce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "fastapi[standard]>=0.128.0",
    "pip>=25.3",
    "python-dotenv>=1.2.1",
]
